// Versioned insurer form definitions for partially filled PDF output.
//
// Each insurer PDF is treated as a software dependency pinned by SHA-256.
// The field names come from the verified research spike
// (Aspire/Research/Fillable PDF Form Filling Feasibility.md, 2026-07-13).
// A new insurer revision must be re-inspected, re-mapped, re-hashed, and
// re-approved before it replaces one of these definitions.
//
// The Quadrus To-table numbering contains real gaps (TextField_106 and
// TextField_113 do not exist), so the arrays below are explicit and must
// never be regenerated by arithmetic.

function segRows(prefix, amountField) {
  const rows = [];
  for (let n = 1; n <= 10; n++) {
    rows.push({
      code: `order.${prefix}[${n}].fundNumber`,
      name: `order.${prefix}[${n}].name`,
      amount: `order.${prefix}[${n}].amount.${amountField}`,
    });
  }
  return rows;
}

function quadrusFromRows() {
  const rows = [];
  for (let n = 0; n < 10; n++) {
    rows.push({
      code: `TextField_${10 + 6 * n}`,
      name: `TextField_${11 + 6 * n}`,
      amount: `TextField_${13 + 6 * n}`,
    });
  }
  return rows;
}

const QUADRUS_TO_CODE = [78, 84, 90, 96, 102, 108, 115, 121, 127, 133];
const QUADRUS_TO_NAME = [79, 85, 91, 97, 103, 110, 116, 122, 128, 134];
const QUADRUS_TO_AMOUNT = [81, 87, 93, 99, 105, 112, 118, 124, 130, 136];

function quadrusToRows() {
  return QUADRUS_TO_CODE.map((c, i) => ({
    code: `TextField_${c}`,
    name: `TextField_${QUADRUS_TO_NAME[i]}`,
    amount: `TextField_${QUADRUS_TO_AMOUNT[i]}`,
  }));
}

export const FORM_DEFS = [
  {
    id: 'seg-switch',
    label: 'Canada Life Seg Fund Switch Form (70-0019, 7/24)',
    shortLabel: 'Seg Fund Switch',
    file: 'forms/seg-fund-switch-70-0019-2024-07.pdf',
    formNumber: '70-0019',
    revision: '7/24 (D)',
    sha256: 'ecab6898d01d4312a1964169a1ada7e0828004780b36407562537e5159ca70f8',
    expectedFieldCount: 141,
    rowLimit: 10,
    fromRows: segRows('investment', 'formattedOrTypeDollarEquivalent'),
    toRows: segRows('targetInvestment', 'valueWithTypeSymbol'),
    notes:
      'One form per segregated fund policy. Only the Switch From and Switch To fund rows are filled; every other field stays blank and fillable.',
  },
  {
    id: 'quadrus-two-sided',
    label: 'Quadrus Two Sided Transaction Form (46-6126, 9/25)',
    shortLabel: 'Quadrus Two Sided',
    file: 'forms/quadrus-two-sided-46-6126-2025-09.pdf',
    formNumber: '46-6126',
    revision: '9/25',
    sha256: '57fdba615db219a8bfa528d3124a6cf325c180c0058f7842288cbf094545970f',
    expectedFieldCount: 138,
    rowLimit: 10,
    fromRows: quadrusFromRows(),
    toRows: quadrusToRows(),
    notes:
      'Mutual fund switches and internal transfers. Only the From and To fund rows are filled; grouping, sales charge, and every other field stay blank and fillable.',
  },
];

export function getFormDef(id) {
  return FORM_DEFS.find(d => d.id === id) || null;
}
